### ISSUE TITLE
Detecting bad configuration URL

### ISSUE THREAD

**Issue by fxn** [kontera-technologies/graphite-api#12]
Hi! More a question than an issue.

I am writing a Ruby service that uses Graphite via TCP, and would like to fail fast at boot to detect configuration errors. Looking at the API, I guess the service could send a dummy metric, but wonder if there is something cleaner, even if it's hacky.

**Comment by eranb** [comment]
@fxn I've just uploaded a new version of `GraphiteAPI` ( Ver. `0.3.2` ) with a new `check!` method   that is now exposed on `GraphiteAPI::Client` class. see example below.
```
➜  github gem install graphite-api -v "0.3.2"
Fetching: zscheduler-0.0.8.gem (100%)
Successfully installed zscheduler-0.0.8
Fetching: graphite-api-0.3.2.gem (100%)
Successfully installed graphite-api-0.3.2
Parsing documentation for zscheduler-0.0.8
Installing ri documentation for zscheduler-0.0.8
Parsing documentation for graphite-api-0.3.2
Installing ri documentation for graphite-api-0.3.2
Done installing documentation for zscheduler, graphite-api after 0 seconds
2 gems installed
➜  github irb
2.4.1 :001 > require 'graphite-api'
 => true 
2.4.1 :002 > client = GraphiteAPI.new graphite: "udp://BAD-HOST:1234"
 => #<GraphiteAPI::Client:0x007f81d42528f0 @options={:backends=>["udp://BAD-HOST:1234"], :cleaner_interval=>43200, :port=>2003, :log_level=>:info, :cache=>nil, :host=>"localhost", :prefix=>[], :interval=>0, :slice=>1, :pid=>"/tmp/graphite-middleware.pid", :direct=>true}, @buffer=#<GraphiteAPI::Buffer:70097793356680 @quque#size=0 @streamer={}>, @connectors=#<GraphiteAPI::Connector::Group:0x007f81d42525d0 @connectors=[#<GraphiteAPI::Connector:70097793356360: udp://BAD-HOST:1234>]>> 
2.4.1 :003 > client.check!
SocketError: udp://BAD-HOST:1234: getaddrinfo: nodename nor servname provided, or not known
	from /Users/eran/.rvm/gems/ruby-2.4.1/gems/graphite-api-0.3.2/lib/graphite-api/connector.rb:71:in `connect'
	from /Users/eran/.rvm/gems/ruby-2.4.1/gems/graphite-api-0.3.2/lib/graphite-api/connector.rb:71:in `block in init_udp'
	from /Users/eran/.rvm/gems/ruby-2.4.1/gems/graphite-api-0.3.2/lib/graphite-api/connector.rb:71:in `tap'
	from /Users/eran/.rvm/gems/ruby-2.4.1/gems/graphite-api-0.3.2/lib/graphite-api/connector.rb:71:in `init_udp'
	from /Users/eran/.rvm/gems/ruby-2.4.1/gems/graphite-api-0.3.2/lib/graphite-api/connector.rb:37:in `socket'
	from /Users/eran/.rvm/gems/ruby-2.4.1/gems/graphite-api-0.3.2/lib/graphite-api/connector.rb:30:in `check!'
	from /Users/eran/.rvm/gems/ruby-2.4.1/gems/graphite-api-0.3.2/lib/graphite-api/connector.rb:89:in `block in check!'
	from /Users/eran/.rvm/gems/ruby-2.4.1/gems/graphite-api-0.3.2/lib/graphite-api/connector.rb:87:in `each'
	from /Users/eran/.rvm/gems/ruby-2.4.1/gems/graphite-api-0.3.2/lib/graphite-api/connector.rb:87:in `check!'
	from /Users/eran/.rvm/gems/ruby-2.4.1/gems/graphite-api-0.3.2/lib/graphite-api/client.rb:22:in `check!'
	from (irb):3
	from /Users/eran/.rvm/rubies/ruby-2.4.1/bin/irb:11:in `<main>'
2.4.1 :004 > 
```

**Comment by fxn** [comment]
That is awesome, thanks a lot! ❤️
-- 
Sent from Gmail Mobile
