### ISSUE TITLE
Error when receiving Errno::ETIMEDOUT that should be rescued

### ISSUE THREAD

**Issue by awaage** [kontera-technologies/graphite-api#9]
I believe this line needs to also rescue the Errno::ETIMEDOUT exception:

https://github.com/kontera-technologies/graphite-api/blob/master/lib/graphite-api/connector.rb#L34

Reproducing:
```
client = GraphiteAPI.new(graphite: "10.10.100.161:2003") 
c = client.instance_variable_get("@connectors")
m = 'pulse-stag.site_101.aw 339.0 1485488850'

# Publish message
c.publish m
D, [2017-01-27T18:08:31.519220 #28605] DEBUG -- : [:connector_group, :publish, 39, [GraphiteAPI::Connector 10.10.100.161:2003]]
D, [2017-01-27T18:08:31.519315 #28605] DEBUG -- : [:connector, :puts, "10.10.100.161:2003", "pulse-stag.site_101.aw 339.0 1485488850"]
 => ["pulse-stag.site_101.aw 339.0 1485488850"] 

# Wait for 30 minutes... then publish again 

2.2.0 :149 > c.publish m
D, [2017-01-27T18:39:00.801402 #28605] DEBUG -- : [:connector_group, :publish, 39, [GraphiteAPI::Connector 10.10.100.161:2003]]
D, [2017-01-27T18:39:00.801480 #28605] DEBUG -- : [:connector, :puts, "10.10.100.161:2003", "pulse-stag.site_101.aw 339.0 1485488850"]
Errno::ETIMEDOUT: Connection timed out
        from /usr/local/rvm/gems/ruby-2.2.0/gems/graphite-api-0.1.6/lib/graphite-api/connector.rb:33:in `write'
        from /usr/local/rvm/gems/ruby-2.2.0/gems/graphite-api-0.1.6/lib/graphite-api/connector.rb:33:in `puts'
        from /usr/local/rvm/gems/ruby-2.2.0/gems/graphite-api-0.1.6/lib/graphite-api/connector.rb:33:in `puts'
        from /usr/local/rvm/gems/ruby-2.2.0/gems/graphite-api-0.1.6/lib/graphite-api/connector.rb:22:in `block (2 levels) in publish'
        from /usr/local/rvm/gems/ruby-2.2.0/gems/graphite-api-0.1.6/lib/graphite-api/connector.rb:22:in `map'
        from /usr/local/rvm/gems/ruby-2.2.0/gems/graphite-api-0.1.6/lib/graphite-api/connector.rb:22:in `block in publish'
        from /usr/local/rvm/gems/ruby-2.2.0/gems/graphite-api-0.1.6/lib/graphite-api/connector.rb:22:in `each'
        from /usr/local/rvm/gems/ruby-2.2.0/gems/graphite-api-0.1.6/lib/graphite-api/connector.rb:22:in `publish'
        from (irb):149
        from /usr/local/rvm/rubies/ruby-2.2.0/bin/irb:11:in `<main>'
```

**Comment by eranb** [comment]
@awaage I pushed a new version, `graphite-api-0.1.7.gem`

thanks

**Comment by awaage** [comment]
@eranb thanks for the quick fix !
